### PR TITLE
nytimes article page clone

### PR DESCRIPTION
**Pull request by tirthajyoti-ghosh**
This static page contains:
- Fixed Navigation Bar
- Article section(contains opening image, share buttons, main article, floated right editor's picks, css sprite implementation, youtube video iframe)
- More news and most popular section
- Footer Links
- Footer

### CODE REVIEW

**Review by imhta — CHANGES_REQUESTED** [review]
# Changes required 🛑 

### Hello  @tirthajyoti-ghosh @sddoe , 👋 You have done a great job in this project 👏 Kudos for pixel-perfect clone
* [x] Stickler is not enabled in this repo or project, enable it. ([reference](https://github.com/microverseinc/linters-config/tree/master/css))
* [x] The NY Times logo is a link ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))


----
### Don't forgot to request for another code review
----
**Pon Muthu Selvam N**
__nponmuthuselvam@gmail.com__
_If you have any queries, feel free to ping me on slack_

**Comment by sddoe** [comment]
We had fixed all of the errors from the last merge pull request, including:

- Enable Stickler in this repo
- Stylized NY Times Logo as a link

**Review by pelzolga123 — CHANGES_REQUESTED** [review]
Validator shows errors in this project.

**Comment by pelzolga123** [comment]
## Hi Team!  
### Your project looks :+1: amazing!
One more thing is left before this project can be approved:
* [x] check HTML markup with this [validator](https://validator.w3.org/#validate_by_upload). Now it shows errors in your project.
### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Comment by sddoe** [comment]
We had fixed all of the errors from the last merge pull request, including:

- Errors and warnings in HTML markup

**Review by pelzolga123 — APPROVED** [review]
Approved.

**Comment by pelzolga123** [comment]
## Great  work, Congratulation :+1: Project Approved.
You did all changes required previously. Go ahead and merge to master.
_Goodluck in your next project_ *Happy coding*

**Pull request merged**
